[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_playground = "HS6fgmD8usW9sBgWBfaZqYzMqW8Gb38Bg58X1NKSe6m4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kaz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
